# Generated by Django 4.2.6 on 2023-11-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('phone_number', models.IntegerField(verbose_name='تلفن همراه')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('email', models.CharField(max_length=80, verbose_name='ایمیل')),
                ('state', models.CharField(max_length=80, verbose_name='استان')),
                ('city', models.CharField(max_length=80, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.IntegerField(verbose_name='تلفن ثابت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('relationship', models.TextField(verbose_name='نحوه آشنایی')),
            ],
        ),
    ]
