# Generated by Django 4.2.6 on 2023-11-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='تعدادکارتن')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='تعدادکل')),
                ('total_of_price', models.IntegerField(verbose_name='قیمت کل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myproduct', to='products.products', verbose_name='محصولات')),
            ],
        ),
    ]
